### ISSUE TITLE
[BUG] Crash on installing with `scoop`

### ISSUE THREAD

**Issue by Ryuo1** [kraanzu/smassh#85]
### Describe the bug 🐛

using `pip` in windows, installed from scoop.
I get this error after I install smassh from pip:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\anshu\scoop\apps\python\current\Scripts\smassh.exe\__main__.py", line 4, in <module>
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\smassh\__init__.py", line 3, in <module>
    from smassh.ui.tui import Smassh
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\smassh\ui\__init__.py", line 1, in <module>
    from .tui import Smassh
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\smassh\ui\tui.py", line 2, in <module>
    from textual import on
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\textual\__init__.py", line 9, in <module>
    from . import constants
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\textual\constants.py", line 10, in <module>
    from typing_extensions import Final, TypeGuard
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\typing_extensions.py", line 1174, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
```

### To Reproduce 🐣

1. use windows (not linux)
2. use pip from scoop
3. install smassh from pip
4. try to open smassh from the terminal
5. cry that this error would not have existed on arch linux

### Expected behavior 🤔

it work

### Your operating system name

Windows

### Your operating system version

23H2

**Comment by kraanzu** [comment]
Hi @Ryuo1, from the error I see that the TUI lib caused the crash and has nothing to do with smassh

I have no idea about Scoop but I'll look into it. Can you also share your Python version? Thanks

> cry that this error would not have existed on Arch Linux

lmao yes

**Comment by Ryuo1** [comment]
Python 3.12.2

**Comment by kraanzu** [comment]
Can you try running this in your python3.12 shell:

```
from typing_extensions import Final, TypeGuard
```

**Comment by Ryuo1** [comment]
```
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from typing_extensions import Final, TypeGuard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anshu\scoop\apps\python\current\Lib\site-packages\typing_extensions.py", line 1174, in <module>
    class TypeVar(typing.TypeVar, _DefaultMixin, _root=True):
TypeError: type 'typing.TypeVar' is not an acceptable base type
```

**Comment by kraanzu** [comment]
Ok so it's a known issue ( see https://github.com/python/typing_extensions/issues/243)
And most likely because you're using Python `3.12`

I've updated the deps, can you retry?

```bash
pip install git+https://github.com/kraanzu/smassh.git
```

**Comment by kraanzu** [comment]
Closing this as stale
